# This is a basic workflow to help you get started with Actions

name: MERN Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the development branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.HOST}}
          key: ${{secrets.KEY}}
          username: ${{secrets.USERNAME}}
          
          script: |
            sudo systemctl stop www
            sudo systemctl stop mongod
            if [ -d "/www/mernactivity21" ]; then rm -rf /www/mernactivity21; fi
            cd /www
            git clone git@github.com:sayex/mernactivity21.git
            cd /www/mernactivity21
            npm run install:prod
            npm run build
            sudo systemctl start mongod
            sudo systemctl start www

