name: merndelpy

on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: ${{secrets.HOST}}
          key: ${{secrets.KEY}}
          username: ${{secrets.USERNAME}}
          
          script: |
            if [-d "/www/mernactivity21"]; then rm -rf /www/mernactivity21; fi
            systemctl start www
            cd /www
            ssh-agent bash -c 'shh-add ~/.ssh/github; git clone git@github.com:sayex/mernactivity21.git'
            cd /www/mernactivity21
            npm run install && npm run build
	          systemctl start www
